artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/artimus07/HeartAttackAnalysis/main/heart_attack_analysis.csv
  local_data_file: heart_attack_analysis.csv

data_validation:
  root_dir: artifacts/data_validation
  DATA_FILE: "D:/HeartAttackAnalysis/artifacts/data_ingestion/heart_attack_analysis.csv"
  STATUS_FILE: artifacts/data_validation/status.txt